model: 'DarkNet53_YOLOv3'
dataset_name: 'Pascal'
classes: 3
in_channels: 3
# train_path: 'D:/datasets/voc/yolo_format/train'
# val_path: 'D:/datasets/voc/yolo_format/val'
# names: 'D:/datasets/voc/yolo_format/voc.names'
train_path: './data'
val_path: './data'
names: './data/test.names'
input_size: 416

workers: 2
epochs: 500
batch_size: 4

save_freq: 5
save_dir: './saved'
gpus: -1

backbone: 'DarkNet53'
varient: 53

optimizer: 'adam'
optimizer_options:
  lr: 1e-3

loss: 'yolo_loss'

trainer_options:
  check_val_every_n_epoch: 5

experimental_options:
  os: 'windows'
  callbacks:
    - 'SWA'